- .vscode/settings.json
We don't need this, since we have `.editorconfig` setting tabs already.
This PR needs an in-depth review.
> chore: 🔨  remove `tabSize` from VS Code settings file

- justfile
I'm not sure that this is the best way to go about it - and as we, @lwjohnst86 , talked about we might want to make a tool for tasks like this at some point. But maybe this is fine for now? 
At least I find this helpful - instead of having to create the function file and corresponding test file by hand.
With this, the command `just add-function sprout core hello` creates `sprout/core/hello.py` and the corresponding test file `tests/core/test_hello.py`
This PR needs a quick review.
> feat: 🧑‍💻 add recipe `add-function`

- .github/sync.yml
- .pre-commit-config.yaml
- README.md
- justfile
This PR adds pre-commit to the repos, which will auto-run commit linting before the commit message is finished.
After this is merged in and sync'ed with Sprout, the spaid command `spaid_setup_dev_workspace` will install everything for this to start working.
Alternatively, this pre-commit will always run on PRs, and will throw an error if a commit message is wrong.
Closes #8, closes seedcase-project/team#89
This PR needs an in-depth review.
> chore: :hammer: add commit linting via pre-commit

- .github/workflows/update-version.yml
The release workflow needs to push back to main, so can't use the `on.pull_request` trigger.
This PR does not need a review.
> ci: :construction_worker: needs to push to main, not from PRs

- .github/pull_request_template.md
- justfile
This PR makes very small updates to the justfile and simplifies the checklist in the PR template to tell submitter to run `just run-all` as a check. 
This PR needs a quick review.
> chore: :technologist: use justfile as checklist in template

- justfile
The `run-all` recipe wasn't updated when `test-python` was renamed from `run-tests` which resulted in an error when using `run-all`. So it is now 👍
This PR needs a quick review.
> fix: add `test-python` to `run-all`

- .vscode/google-notypes.mustache
Since we generally want to add examples to our Python functions (but maybe not all functions?), I have added it to the docstring template.
Thoughts? Feel free to disagree.
This PR needs an in-depth review.
> feat: :sparkles: add examples section to docstring template

- justfile
I found a bug in the justfile recipe that made the check commit not work correctly. This fixed it.
Doesn't need a review
> fix: :hammer: the `check-commits` recipe wasn't correctly checking them

- justfile
If the qmd files don't exist, `rm` gives an error. So this is to force it to not give an error.
Doesn't need a review.
> build: :bug: `rm` needs `-f` so it doesn't error when there is no file

- .github/workflows/add-to-project.yml
Reflecting the update in `.github` repo.
No review necessary.
> ci: :construction_worker: switch to use the reusable "add to board"

- .gitignore
- justfile
Adds justfile steps to run coverage and make the report and badge.
Doesn't need a review
> build: :hammer: build coverage report and badge

- .github/workflows/build-package.yml
Based on the changes in the `.github` repo, the lint workflow was removed and merged into a general "build" workflow. So this matches that workflow.
Doesn't need a review.
> ci: :construction_worker: lint is now part of build workflow

- .vscode/extensions.json
- .vscode/settings.json
This removes the `cSpell` vscode extension, replaces it with `typos` extension. And removes some leftover extensions we don't need.
Closes #37
> chore: :wrench: remove leftover extensions, replace spell checker

- .github/workflows/update-version.yml
Adds the app id for the reusable workflow.
> ci: :lock: use GitHub App for short-lived token creation

- .github/workflows/add-to-project.yml
Simple fix, of adding the `app-id`
Doesn't need a review.
> ci: :construction_worker: update to use GitHub App for adding to board

- .github/workflows/build-website.yml
When using badges, it takes it from the name. So this is a small improvement to have the workflow name shorter.
Doesn't need a review.
> ci: :memo: use a shorter name for workflow

- .github/workflows/sync-files.yml
Use the GitHub App to make a token for syncing.
> ci: :construction_worker: use GitHub App token for syncing files

- .github/workflows/sync-files.yml
The workflow needs this config field.
> ci: :bug: needs to be `GH_INSTALLATION_TOKEN` for GitHub Apps

- justfile
Syncs what has been done in Sprout.
> build: :hammer: update justfile with recipes from Sprout

- justfile
So that anyone who contributes will trigger pre-commit hooks right away.
This PR needs a quick review.
> build: :hammer: add a "install pre-commit" justfile recipe

- .github/sync.yml
- .github/workflows/dependency-review.yml
- .github/workflows/scorecards.yml
Adds the security workflows, using the reusable ones I made, so that they get synced.
> ci: :lock: add security scanning workflows

- .vscode/python.code-snippets
Match what was done in Sprout.
> chore: :wrench: fix spacing for snippet, use 4 spaces, not 1

- .vscode/extensions.json
The MS version of the mypy extension was not as well reviewed. This one is better, plus, the setting used in `settings.json` was for this extension, not the other one.
> chore: :technologist: recommend better reviewed mypy extension
